config/routes.rb
Resistance::Application.routes.draw do

  root :to => 'users#new'

  resources :game_invitees, only: [:new, :create] 
  resources :games, only: [:new, :create, :show] 

  resources :user_sessions

  get 'login' => "user_sessions#new", as: :login
  post 'logout' => "user_sessions#destroy", as: :logout

  resources :users
  resource :user, :as => 'account'

  get 'signup' => 'users#new', :as => :signup

end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic do |c|
		# optional config block
		c.login_field = :login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :login_required, :only => [:show, :edit]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /user
  def show
    @user = current_user
  end

  # GET /users/1/edit
  # GET /user/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to account_url, notice: 'User was successfully created.'
    else
      render :action => :new
    end
  end

  # PATCH/PUT /user
  def update
    if @user.update_attributes(user_params)
      redirect_to account_url, notice: 'User was successfully updated.'
    else
      render :action => :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :login, :email, :password, :password_confirmation)
    end

    # Require a logged-in session with this method
    # Method current_user is defined in ApplicationController.rb
    def login_required  
    unless current_user  
      flash[:error] = 'You must be logged in to view this page.'  
      redirect_to new_user_session_path  
    end  
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render "shared/error_messages", :target => @user %>

<p>
  <%= form.label :name %><br />
  <%= form.text_field :name %>
</p>
<p>
  <%= form.label :login %><br />
  <%= form.text_field :login %>
</p>
<p>
  <%= form.label :email %><br />
  <%= form.text_field :email %>
</p>
<p>
  <%= form.label :password, form.object.new_record? ? nil : "Change password" %><br />
  <%= form.password_field :password %>
</p>
<p>
  <%= form.label :password_confirmation %><br />
  <%= form.password_field :password_confirmation %>
</p>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for @user do |f| %>
	<%= render :partial => "form", :object => f, :locals => { user: @user } %>
	<%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<h1>Register</h1>

<%= form_for @user do |f| %>
	<%= render :partial => "form", :object => f, :locals => { :user => @user } %>
	<%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <b>Login count:</b>
  <%=h @user.login_count %>
</p>

<p>
  <b>Last request at:</b>
  <%=h @user.last_request_at %>
</p>

<p>
  <b>Last login at:</b>
  <%=h @user.last_login_at %>
</p>

<p>
  <b>Current login at:</b>
  <%=h @user.current_login_at %>
</p>

<p>
  <b>Last login ip:</b>
  <%=h @user.last_login_ip %>
</p>

<p>
  <b>Current login ip:</b>
  <%=h @user.current_login_ip %>
</p>

<%= link_to 'Edit Account', edit_account_path %>