config/routes.rb
Resistance::Application.routes.draw do

  root :to => 'users#new'

  resources :game_invitees, only: [:new, :create] 
  resources :games, only: [:new, :create, :show] 

  resources :user_sessions

  get 'login' => "user_sessions#new", as: :login
  post 'logout' => "user_sessions#destroy", as: :logout

  resources :users
  resource :user, :as => 'account'

  get 'signup' => 'users#new', :as => :signup

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :game_invitees, inverse_of: :game
	has_many :game_options, inverse_of: :game
	has_many :players, inverse_of: :game
	has_many :game_rounds, inverse_of: :game
	belongs_to :creator, class_name: 'User'

	validates :title, presence: true
	validates :status, inclusion: { in: GameStatus.all.map { |s| s.value } }
	validates :player_count, presence: true
	validates :creator_id, presence: true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	# GET /games
	def index
		@games = Game.order(created_at: :desc)
		# render games/index.html.erb
	end

	# GET /games/1
	def show
		@game = Game.find(params[:id])
	end

	# GET /games/new
	def new
		@game = Game.new
		# render games/new.html.erb
	end

	# POST /games
	def create
		@game = Game.new(game_params)
		@game.status = GameStatus::WAITING_FOR_PLAYERS
		@game.creator_id = current_user.id
		saved = @game.save
		if saved
			redirect_to games_url, :notice => 'Your game was created. Invite some people to play!'
		else
			render :action => :new
		end
	end

	private
		def game_params
			params.require(:game)
				.permit(:title, :player_count)
		end
end

app/helpers/games_helper.rb
module GamesHelper
	def get_status_display (game)
		case game.status
		when GameStatus::CANCELLED
			"Cancelled"
		when GameStatus::WAITING_FOR_PLAYERS
			"Waiting for players to join"
		when GameStatus::IN_PROGRESS
			"In progress"
		when GameStatus::COMPLETED
			"Completed"
		else
			raise "Unrecognized game status for game #{game.id}"
		end
	end

	def valid_player_counts
		return (5..10).to_a
	end

	def get_view_for_status (game)
		case game.status
		when GameStatus::CANCELLED
			'cancelled'
		when GameStatus::WAITING_FOR_PLAYERS
			'waiting_for_players'
		when GameStatus::IN_PROGRESS
			'in_progress'
		when GameStatus::COMPLETED
			'complete'
		else
			raise "Unrecognized game status for game #{game.id}"
		end
	end
end

app/views/games/_in_progress.html.erb
in progress

app/views/games/_waiting_for_players.html.erb
<h2>Waiting for players to join...</h2>

<h3>Joined players</h3>

<% invitees1 = GameInvitee.where(game_id: @game.id, is_joined: true).includes(:user) %>
<ul>
<% invitees1.each do |i| %>
	<li><%= i.user.name %> (<%= i.user.login %>)</li>
<% end %>
</ul>


<h3>Invite pending players</h3>
<% invitees2 = GameInvitee.where(game_id: @game.id, is_joined: false).includes(:user) %>
<ul>
<% invitees2.each do |i| %>
	<li><%= i.user.name %> (<%= i.user.login %>)</li>
<% end %>
</ul>


<h3>Invite a player</h3>

<div style="width:400px">
<%=
widget(:item_selector, 'userSelector1')
	.empty_text("Select a user 1")
	.render
%>
<%=
widget(:item_selector, 'userSelector2')
	.empty_text("Select a user 2")
	.render
%>
<%=
widget(:item_selector, 'userSelector3')
	.empty_text("Select a user 3")
	.render
%>
<%=
widget(:item_selector, 'userSelector4')
	.empty_text("Select a user 4")
	.render
%>
</div>

app/views/games/index.html.erb
<h1>My Games</h1>

<p id="notice"><%= notice %></p>

<table>
	<thead><tr>
		<th>Game</th>
		<th>Creator</th>
		<th>Number of players</th>
		<th>Status</th>
	</tr></thead>
	<tbody>
	<% @games.each do |game| %>
		<tr>
			<td>
				<% if game.status == GameStatus::WAITING_FOR_PLAYERS or game.status == GameStatus::IN_PROGRESS %>
					<%= link_to game.title, game %>
				<% else %>
					game.title
				<% end %>
			</td>
			<td><%= game.creator.name %></td>
			<td>(<%= game.player_count %> players)</td>
			<td><%= get_status_display game %></td>
		</tr>
	</tbody>
	<% end %>
</table>

<%= link_to 'Create new game', new_game_url %>

<div>
	<%= widget 'test', "test1", { test_string: ":)" } %>
	<%= widget 'test', "test2", { test_string: ":(" } %>
	<%= widget 'test', "test3", { test_string: ":P" } %>
	<%= widget 'test', "test4", { test_string: "^.^" } %>
</div>

app/views/games/new.html.erb
<%= render "shared/error_messages", :target => @game %>

<%= form_for @game do |form| %>
	<p>
	  <%= form.label :title %><br />
	  <%= form.text_field :title %>
	</p>
	<p>
	  <%= form.label :player_count %><br />
	  <%= form.collection_select :player_count, valid_player_counts, :to_s, :to_s, {:prompt => true} %>
	</p>
	<%= form.submit "Create" %>
<% end %>

app/views/games/show.html.erb
<h1><%= @game.title %></h1>
<hr>
<%= render :partial => get_view_for_status(@game) %>