config/routes.rb
Resistance::Application.routes.draw do

  root :to => 'users#new'

  resources :game_invitees, only: [:new, :create] 
  resources :games, only: [:new, :create, :show] 

  resources :user_sessions

  get 'login' => "user_sessions#new", as: :login
  post 'logout' => "user_sessions#destroy", as: :logout

  resources :users
  resource :user, :as => 'account'

  get 'signup' => 'users#new', :as => :signup

end

app/views/layouts/_widget.html.erb
<% 
# This file is the single layout for all widget partials.
%>

<%
# Wrap all widgets in a div with class name of their widget instance uuid.
# This is necessary for binding the widget instance object in javascript to the
# correct html element.
# Additionally, a class is applied to designate this as a widget built by this framework.
# Finally, a class name with the widget type is added, so that all widgets
# of the same type can be selected easily if desired.
%>
<%=
content_tag :div, {
	:class => ['jj-widget', widget_template_info[:widget_type]],
	:id => widget_template_info[:widget_id]
} do 
%>
	<%= yield %>
<% end %>

<% 
# When this widget file is done rendering, reset the current widget context to this
# widget's parent widget context (which may be null if this widget is on the top-level page).
# This is required by the widget framework in order to manage which widget instances are
# contained in other widget instances.
%>
<% widget_framework.set_widget_context widget_template_info[:parent_widget_context] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resistance</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="nav">
    <% if current_user %>
    	<%= link_to "My Account", account_path %>
    	<%= link_to "Log Out", logout_path, :method => :post %>
    <% else %>
    	<%= link_to "Register", new_user_path %> | 
    	<%= link_to "Log In", login_path %>
    <% end %>
  </div>

<%= yield %>
<% widget_framework.finish_widgets %>

<%= widget_framework.all_required_widgets_style self %>
<%= widget_framework.all_required_widgets_js self %>
<%= javascript_tag do %>
  <%= raw(render :partial => "widgets/widget") %>
<% end %>
</body>
</html>